### ISSUE TITLE
[BUG]: HS103 Plug Not Showing up...

### ISSUE THREAD

**Issue by Jon-So** [jneilliii/OctoPrint-TPLinkSmartplug#229]
**Describe the bug**
The plug Hs103 is added but doesn't show up on the list once it's created

**To Reproduce**

I have it shown on the other printers with no problem...

**Expected behavior**

When you add the plug it's not visible but it's there...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] Mozilla Firefox 
 - OctoPrint Version [e.g. 22] 1.5.2, python 3.7.3 Octopi 0.17.0
 - Plugin Version 0.9.26

**Additional context**

**Comment by Jon-So** [comment]
![Uploading 102045583...]

**Comment by Jon-So** [comment]
![image](https://user-images.githubusercontent.com/72947968/102045647-6be8c780-3d8e-11eb-8ba9-cce5de842620.jpeg)

**Comment by Jon-So** [comment]
I did an uninstall and a reinstall and I cant seem to see the plug nor its settings... :(

**Comment by jneilliii** [comment]
Is the plugin getting disabled?

**Comment by Jon-So** [comment]
No it's not disabled, it still works but I can't see the plug that was there nor can I add or edit it's settings

**Comment by jneilliii** [comment]
That issue was something that should have been fixed in 0.9.25 and would only show like this if you have another plugin that might be causing a conflict with jQuery sortable. Do you have Custom Controls or System Command Editor installed?

**Comment by Jon-So** [comment]
Ok so when I removed unnecessary plugins it was still not showing up, then I updated the Ocotprint-WideScreen to the latest and then it showed up. And I noticed why there was an extra bolt icon in my Navbar and I was able to see everything again... so it might have something to do with the widescreen plugin... but I could be mistaken... either way problem solved!!!
